[tool.poetry]
name = "graphai"
version = "0.0.1"
description = ""
authors = ["\"Aurelio AI\" <hello@aurelio.ai>"]
readme = "README.md"
packages = [{include = "graphai"}]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
semantic-router = "^0.0.54"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.25.0"
ruff = "^0.1.5"
pytest = "^7.4.3"
pytest-mock = "^3.12.0"
pytest-cov = "^4.1.0"
pytest-xdist = "^3.5.0"
mypy = "^1.7.1"
black = {extras = ["jupyter"], version = ">=23.12.1,<24.5.0"}

[tool.poetry.extras]
visualize = ["networkx", "matplotlib"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
