name: Release

on:
  push:
    tags:
    - '*'

env:
  UV_VERSION: "0.1.19"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    - name: Cache uv
      uses: actions/cache@v4
      with:
        path: ~/.cache/uv
        key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-uv-
    - name: Install uv
      run: |
        pip install uv==$UV_VERSION
    - name: Install dependencies
      run: |
        uv pip install -e ".[dev]"
    - name: Build
      run: |
        uv pip install build
        uv run python -m build

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    - name: Cache uv
      uses: actions/cache@v4
      with:
        path: ~/.cache/uv
        key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-uv-
    - name: Install uv
      run: |
        pip install uv==$UV_VERSION
    - name: Install publishing tools
      run: |
        uv pip install build twine
    - name: Build and publish to PyPI
      run: |
        uv run python -m build
        uv run twine upload dist/* --username "__token__" --password "$PYPI_API_TOKEN"
      env:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
